version: '3.9'
services:
  nestapp:
    container_name: nestapp_dev
    build:
      target: dev
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app

  db:
    container_name: db_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
