version: '3.9'
services:
  nestapp:
    container_name: nestapp_prod
    build:
      target: prod
    image: jungmini0601/nest-auth-example:1.0.0
    environment:
      - NODE_ENV=prod

  db:
    container_name: db_prod
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
