version: '3.9'
services:
  nestapp:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
